name: Build bindings for Windows releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22

        architecture:
          - x64
          - x86

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}

      - name: Install Visual Studio 2019 Build Tools
        run: |
            choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
  
      - run: npm config set msvs_version 2019
      - name: Install packages
        run: npm install
        env:
          SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
          # GYP_MSVS_VERSION: 2019  # Keep in sync with the Visual Studio version installed above

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v4
        if: github.repository_owner == 'sass' && github.event_name != 'pull_request'
        with:
          name: ${{ matrix.node }}-${{ matrix.architecture }}
          path: |
            vendor/**/binding.node
            build/Release/binding.pdb
