name: Build bindings for Windows releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22

        architecture:
          - x64
          - x86

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}

      - name: Setup Python
        if: matrix.architecture == 'x86'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Windows build tools
        if: matrix.architecture == 'x86'
        run: |
          # Install Visual Studio Build Tools for x86 builds
          npm install --global --production windows-build-tools
          # Set Python path for node-gyp
          npm config set python python
        shell: powershell

      - name: Clear npm cache
        if: matrix.node == 22 && matrix.architecture == 'x86'
        run: npm cache clean --force
        shell: powershell

      - name: Install packages
        run: npm install --unsafe-perm
        env:
          SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
        shell: powershell

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v4
        if: github.repository_owner == 'sass' && github.event_name != 'pull_request'
        with:
          name: ${{ matrix.node }}-${{ matrix.architecture }}
          path: |
            vendor/**/binding.node
            build/Release/binding.pdb
